### ISSUE TITLE
Suggestions for the list

### ISSUE THREAD

**Issue by anotherik** [guardrailsio/awesome-golang-security#5]
Hi,
Some suggestions for the curated list:

For the **Web Framework Hardening**:  
- [beego-security-headers](https://github.com/gosecguy/beego-security-headers) - beego framework filter for easy security headers management.

For the **Articles, Guides & Talks**:  
- [ReDoS in Go](https://www.checkmarx.com/2018/05/07/redos-go/) by Checkmarx - Diving Deep into Regular Expression Denial of Service (ReDoS) in Go

Thanks for the great list.

**Comment by streichsbaer** [comment]
Thanks for the suggestions @anotherik. Have added them to the list.
